
export const INITIAL_VOCABULARY = [
  { ngaju: "narai", indonesian: "Apa", category: "Umum" },
  { ngaju: "pue", indonesian: "Adik", category: "Keluarga" },
  { ngaju: "kaka", indonesian: "Kakak", category: "Keluarga" },
  { ngaju: "bapa", indonesian: "Bapak", category: "Keluarga" },
  { ngaju: "uma", indonesian: "Ibu", category: "Keluarga" },
  { ngaju: "bue", indonesian: "Kakek", category: "Keluarga" },
  { ngaju: "tambo", indonesian: "Nenek", category: "Keluarga" },
  { ngaju: "anak", indonesian: "Anak", category: "Keluarga" },
  { ngaju: "esun", indonesian: "Cucu", category: "Keluarga" },
  { ngaju: "kawal", indonesian: "Teman", category: "Umum" },
  { ngaju: "oloh", indonesian: "Orang", category: "Umum" },
  { ngaju: "hatalla", indonesian: "Tuhan", category: "Umum" },
  { ngaju: "pambelum", indonesian: "Hidup", category: "Umum" },
  { ngaju: "pampatei", indonesian: "Mati", category: "Umum" },
  { ngaju: "humila", indonesian: "Jahat", category: "Sifat" },
  { ngaju: "bahalap", indonesian: "Baik", category: "Sifat" },
  { ngaju: "bagawi", indonesian: "Bekerja", category: "Kegiatan" },
  { ngaju: "balajar", indonesian: "Belajar", category: "Kegiatan" },
  { ngaju: "kuman", indonesian: "Makan", category: "Kegiatan" },
  { ngaju: "mihup", indonesian: "Minum", category: "Kegiatan" },
  { ngaju: "batiruh", indonesian: "Tidur", category: "Kegiatan" },
  { ngaju: "misik", indonesian: "Bangun", category: "Kegiatan" },
  { ngaju: "mandui", indonesian: "Mandi", category: "Kegiatan" },
  { ngaju: "mentai", indonesian: "Jemur", category: "Kegiatan" },
  { ngaju: "mili", indonesian: "Beli", category: "Kegiatan" },
  { ngaju: "manjual", indonesian: "Jual", category: "Kegiatan" },
  { ngaju: "hadari", indonesian: "Lari", category: "Kegiatan" },
  { ngaju: "nandai", indonesian: "Mendaki", category: "Kegiatan" },
  { ngaju: "penda", indonesian: "Bawah", category: "Arah" },
  { ngaju: "hunjut", indonesian: "Atas", category: "Arah" },
  { ngaju: "gantau", indonesian: "Kanan", category: "Arah" },
  { ngaju: "sambil", indonesian: "Kiri", category: "Arah" },
  { ngaju: "ngaju", indonesian: "Hulu", category: "Arah" },
  { ngaju: "ngawa", indonesian: "Hilir", category: "Arah" },
  { ngaju: "uran", indonesian: "Hujan", category: "Alam" },
  { ngaju: "andau", indonesian: "Hari", category: "Waktu" },
  { ngaju: "malem", indonesian: "Malam", category: "Waktu" },
  { ngaju: "jewu", indonesian: "Besok", category: "Waktu" },
  { ngaju: "benteng andau", indonesian: "Siang", category: "Waktu" },
  { ngaju: "sungei", indonesian: "Sungai", category: "Alam" },
  { ngaju: "danau", indonesian: "Danau", category: "Alam" },
  { ngaju: "tasik", indonesian: "Laut", category: "Alam" },
  { ngaju: "bukit", indonesian: "Bukit", category: "Alam" },
  { ngaju: "gunung", indonesian: "Gunung", category: "Alam" },
  { ngaju: "petak", indonesian: "Tanah", category: "Alam" },
  { ngaju: "kayu", indonesian: "Kayu", category: "Alam" },
  { ngaju: "kembang", indonesian: "Bunga", category: "Alam" },
  { ngaju: "buah", indonesian: "Buah", category: "Alam" },
  { ngaju: "handipe", indonesian: "Ular", category: "Hewan" },
  { ngaju: "bakei", indonesian: "Monyet", category: "Hewan" },
  { ngaju: "hadangan", indonesian: "Kerbau", category: "Hewan" },
  { ngaju: "sapi", indonesian: "Sapi", category: "Hewan" },
  { ngaju: "bawoi", indonesian: "Babi", category: "Hewan" },
  { ngaju: "manuk", indonesian: "Ayam", category: "Hewan" },
  { ngaju: "bebek", indonesian: "Bebek", category: "Hewan" },
  { ngaju: "asu", indonesian: "Anjing", category: "Hewan" },
  { ngaju: "pusa", indonesian: "Kucing", category: "Hewan" },
  { ngaju: "burung", indonesian: "Burung", category: "Hewan" },
  { ngaju: "lauk", indonesian: "Ikan", category: "Hewan" },
  { ngaju: "udang", indonesian: "Udang", category: "Hewan" },
  { ngaju: "kanai", indonesian: "Perut", category: "Anggota Tubuh" },
  { ngaju: "pusar", indonesian: "Pusar", category: "Anggota Tubuh" },
  { ngaju: "tulang", indonesian: "Tulang", category: "Anggota Tubuh" },
  { ngaju: "upak", indonesian: "Kulit", category: "Anggota Tubuh" },
  { ngaju: "balau", indonesian: "Rambut", category: "Anggota Tubuh" },
  { ngaju: "takuluk", indonesian: "Kepala", category: "Anggota Tubuh" },
  { ngaju: "bau", indonesian: "Muka", category: "Anggota Tubuh" },
  { ngaju: "mate", indonesian: "Mata", category: "Anggota Tubuh" },
  { ngaju: "urung", indonesian: "Hidung", category: "Anggota Tubuh" },
  { ngaju: "pinding", indonesian: "Telinga", category: "Anggota Tubuh" },
  { ngaju: "nyame", indonesian: "Mulut", category: "Anggota Tubuh" },
  { ngaju: "kasinga", indonesian: "Gigi", category: "Anggota Tubuh" },
  { ngaju: "biwih", indonesian: "Bibir", category: "Anggota Tubuh" },
  { ngaju: "jela", indonesian: "Lidah", category: "Anggota Tubuh" },
  { ngaju: "uyat", indonesian: "Leher", category: "Anggota Tubuh" },
  { ngaju: "lenge", indonesian: "Tangan", category: "Anggota Tubuh" },
  { ngaju: "pai", indonesian: "Kaki", category: "Anggota Tubuh" },
  { ngaju: "silu", indonesian: "Kuku", category: "Anggota Tubuh" },
  { ngaju: "seluwar", indonesian: "Celana", category: "Benda" },
  { ngaju: "rumah", indonesian: "Rumah", category: "Benda" },
  { ngaju: "batunggang", indonesian: "Pintu", category: "Benda" },
  { ngaju: "basenguk", indonesian: "Jendela", category: "Benda" },
  { ngaju: "rajin", indonesian: "Rajin", category: "Sifat" },
  { ngaju: "salamat kuman", indonesian: "Selamat makan", category: "Sapaan" },
  { ngaju: "buah buah", indonesian: "Hati-hati", category: "Sapaan" },
  { ngaju: "manyarak", indonesian: "Menyisir", category: "Kegiatan" },
  { ngaju: "kento", indonesian: "kalian", category: "Lainnya" },
  { ngaju: "manyarui", indonesian: "menyisir", category: "Lainnya" },
  { ngaju: "sungei", indonesian: "sungai", category: "Lainnya" },
  { ngaju: "hila", indonesian: "sebelah", category: "Lainnya" },
  { ngaju: "hila ngaju", indonesian: "sebelah hulu", category: "Lainnya" },
  { ngaju: "beken", indonesian: "lain", category: "Lainnya" },
  { ngaju: "keabawak", indonesian: "sebuah, buah", category: "Lainnya" },
  { ngaju: "tempon", indonesian: "memiliki", category: "Lainnya" },
  { ngaju: "sarita", indonesian: "cerita", category: "Lainnya" },
  { ngaju: "uka", indonesian: "supaya", category: "Lainnya" },
  { ngaju: "ingatawan", indonesian: "diketahui", category: "Lainnya" },
  { ngaju: "kalombah", indonesian: "lebar", category: "Lainnya" },
  { ngaju: "kalombahie", indonesian: "lebarnya", category: "Lainnya" },
  { ngaju: "tapakan", indonesian: "ujung", category: "Lainnya" },
  { ngaju: "bara", indonesian: "dari", category: "Lainnya" },
  { ngaju: "jetoh", indonesian: "ini", category: "Lainnya" },
  { ngaju: "nyelo", indonesian: "tahun", category: "Lainnya" },
  { ngaju: "je halau", indonesian: "yang lalu", category: "Lainnya" },
  { ngaju: "leteng", indonesian: "tenggelam", category: "Lainnya" },
  { ngaju: "bihin huruan", indonesian: "dahulu kala", category: "Lainnya" },
  { ngaju: "sahindai", indonesian: "sebelum", category: "Lainnya" },
  { ngaju: "lewu", indonesian: "desa", category: "Lainnya" },
  { ngaju: "ingara", indonesian: "dikira", category: "Lainnya" },
  { ngaju: "aran", indonesian: "nama", category: "Lainnya" },
  { ngaju: "pambelom", indonesian: "penghidupan", category: "Lainnya" },
  { ngaju: "sukup", indonesian: "cukup", category: "Lainnya" },
  { ngaju: "panginan", indonesian: "makan", category: "Lainnya" },
  { ngaju: "kebutuhan", indonesian: "kebutuhan", category: "Lainnya" },
  { ngaju: "balimpah ruah", indonesian: "berlimpah ruah", category: "Lainnya" },
  { ngaju: "ianut", indonesian: "diaut", category: "Lainnya" },
  { ngaju: "into kueh", indonesian: "di mana", category: "Lainnya" },
  { ngaju: "malalus", indonesian: "melaksanana", category: "Lainnya" },
  { ngaju: "ritual", indonesian: "ritual", category: "Lainnya" },
  { ngaju: "sanutara", indonesian: "selalu", category: "Lainnya" },
  { ngaju: "sakalepah", indonesian: "sekuat", category: "Lainnya" },
  { ngaju: "handari", indonesian: "lari", category: "Lainnya" },
  { ngaju: "tadsak", indonesian: "terdesak", category: "Lainnya" },
  { ngaju: "himba", indonesian: "hutan", category: "Lainnya" },
  { ngaju: "tolah", indonesian: "inilah", category: "Lainnya" },
  { ngaju: "halui", indonesian: "kembali", category: "Lainnya" },
  { ngaju: "maatur", indonesian: "mengatur", category: "Lainnya" },
  { ngaju: "manggunakan", indonesian: "menggunakan", category: "Lainnya" },
  { ngaju: "sanjata", indonesian: "senjata", category: "Lainnya" },
  { ngaju: "tradisional", indonesian: "tradisional", category: "Lainnya" },
  { ngaju: "sipet", indonesian: "sumpit", category: "Lainnya" },
  { ngaju: "mandau", indonesian: "mandau", category: "Lainnya" },
  { ngaju: "tombak", indonesian: "tombak", category: "Lainnya" },
  { ngaju: "samangat", indonesian: "semangat", category: "Lainnya" },
  { ngaju: "bahasil", indonesian: "berhasil", category: "Lainnya" },
  { ngaju: "menampakalah", indonesian: "mengalahkan", category: "Lainnya" },
  { ngaju: "panyarangan", indonesian: "penyerangan", category: "Lainnya" },
  { ngaju: "sinde toh", indonesian: "sekali ini", category: "Lainnya" },
  { ngaju: "ilengkapi", indonesian: "di lengkapi", category: "Lainnya" },
  { ngaju: "kabakas", indonesian: "ketuaan", category: "Lainnya" },
  { ngaju: "panggantie", indonesian: "pengganti nya", category: "Lainnya" },
  { ngaju: "induan", indonesian: "di ambil", category: "Lainnya" },
  { ngaju: "matie", indonesian: "mati", category: "Lainnya" },
  { ngaju: "tande", indonesian: "henti", category: "Lainnya" },
  { ngaju: "tande tande", indonesian: "henti henti", category: "Lainnya" },
  { ngaju: "balampah", indonesian: "bertapa", category: "Lainnya" },
  { ngaju: "palampah", indonesian: "pertama", category: "Lainnya" },
  { ngaju: "mengamuk", indonesian: "mengamuk", category: "Lainnya" },
  { ngaju: "kaslake", indonesian: "keganasannya", category: "Lainnya" },
  { ngaju: "mambalik", indonesian: "membalik", category: "Lainnya" },
  { ngaju: "mahampas", indonesian: "menghempas", category: "Lainnya" },
  { ngaju: "mangahem", indonesian: "mengaramka", category: "Lainnya" },
  { ngaju: "mampeleteng", indonesian: "meneggelaml", category: "Lainnya" },
  { ngaju: "tuyukan", indonesian: "gundukan", category: "Lainnya" },
  { ngaju: "kasalamatan", indonesian: "keselamatan", category: "Lainnya" },
  { ngaju: "ewen", indonesian: "mereka", category: "Lainnya" },
  { ngaju: "bakas bakas", indonesian: "tua tua", category: "Lainnya" },
  { ngaju: "inyewot", indonesian: "di sebut", category: "Lainnya" },
  { ngaju: "manjaga", indonesian: "menjaga", category: "Lainnya" },
  { ngaju: "tratuma", indonesian: "terutama", category: "Lainnya" },
  { ngaju: "katika", indonesian: "ketika", category: "Lainnya" },
  { ngaju: "getem", indonesian: "tualan", category: "Lainnya" },
  { ngaju: "kakasaran", indonesian: "kekasaran", category: "Lainnya" },
  { ngaju: "meramopas", indonesian: "merampas", category: "Lainnya" },
  { ngaju: "bawi", indonesian: "perempuan", category: "Lainnya" },
  { ngaju: "bujang", indonesian: "gadis", category: "Lainnya" },
  { ngaju: "tatarik", indonesian: "tertarik", category: "Lainnya" },
  { ngaju: "bahalap bahalap", indonesian: "baik baik", category: "Lainnya" },
  { ngaju: "sakaltar", indonesian: "sekitar", category: "Lainnya" },
  { ngaju: "tantara", indonesian: "tentara", category: "Lainnya" },
  { ngaju: "nampara", indonesian: "mulai", category: "Lainnya" },
  { ngaju: "manampa", indonesian: "membuat", category: "Lainnya" },
  { ngaju: "kasingi", indonesian: "kemarahan", category: "Lainnya" },
  { ngaju: "mangkeme", indonesian: "merasa", category: "Lainnya" },
  { ngaju: "manggempur", indonesian: "menggempur", category: "Lainnya" },
  { ngaju: "kajarie", indonesian: "akhirnya", category: "Lainnya" },
  { ngaju: "ingawuk", indonesian: "di timbun", category: "Lainnya" },
  { ngaju: "lembut", indonesian: "timbul", category: "Lainnya" },
  { ngaju: "hujon", indonesian: "atas", category: "Lainnya" },
  { ngaju: "inumbu", indonesian: "ditumbuhi", category: "Lainnya" },
  { ngaju: "are macam", indonesian: "banyak macam", category: "Lainnya" },
  { ngaju: "timbau", indonesian: "bibir", category: "Lainnya" },
  { ngaju: "panggau", indonesian: "pencari", category: "Lainnya" },
  { ngaju: "laok", indonesian: "ikan", category: "Lainnya" },
  { ngaju: "panggau laok", indonesian: "pencari ikan", category: "Lainnya" },
  // Tambahan dari gambar - Kategori Lainnya
  { ngaju: "hai toto", indonesian: "Besar sekali", category: "Lainnya" },
  { ngaju: "sumbu", indonesian: "Lampu", category: "Lainnya" },
  { ngaju: "inampayah", indonesian: "Dilihat", category: "Lainnya" },
  { ngaju: "auh", indonesian: "Bunyi, suara", category: "Lainnya" },
  { ngaju: "bagare", indonesian: "Bernama", category: "Lainnya" },
  { ngaju: "bahalap", indonesian: "Merdu, cantik", category: "Lainnya" },
  { ngaju: "bahali", indonesian: "Sulit", category: "Lainnya" },
  { ngaju: "balampah", indonesian: "Bertapa", category: "Lainnya" },
  { ngaju: "bapagar", indonesian: "Berpagar", category: "Lainnya" },
  { ngaju: "basewot", indonesian: "Terkenal", category: "Lainnya" },
  { ngaju: "belom", indonesian: "Hidup", category: "Lainnya" },
  { ngaju: "bua", indonesian: "Buah", category: "Lainnya" },
  { ngaju: "gitan", indonesian: "Kelihatan", category: "Lainnya" },
  { ngaju: "hamalem", indonesian: "Malam", category: "Lainnya" },
  { ngaju: "hapisah", indonesian: "Berpisah", category: "Lainnya" },
  { ngaju: "hila ngaju", indonesian: "Arah hulu, sebelah hulu", category: "Lainnya" },
  { ngaju: "huma", indonesian: "Rumah", category: "Lainnya" },
  { ngaju: "hunjon", indonesian: "Atas", category: "Lainnya" },
  { ngaju: "imbul", indonesian: "Tanam", category: "Lainnya" },
  { ngaju: "inggosoke", indonesian: "Digosoknya", category: "Lainnya" },
  { ngaju: "kahaian", indonesian: "Kebesaran", category: "Lainnya" },
  { ngaju: "kajadian", indonesian: "Kejadian", category: "Lainnya" },
  { ngaju: "kalawan", indonesian: "Terangnya", category: "Lainnya" },
  { ngaju: "ayu ayu", indonesian: "Masing masing", category: "Lainnya" },
  { ngaju: "baguna", indonesian: "Berguna", category: "Lainnya" },
  { ngaju: "bahaya", indonesian: "Bahaya", category: "Lainnya" },
  { ngaju: "balasut", indonesian: "Panas", category: "Lainnya" },
  { ngaju: "bara", indonesian: "Dari", category: "Lainnya" },
  { ngaju: "baya", indonesian: "Hanya", category: "Lainnya" },
  { ngaju: "benteng", indonesian: "Benteng", category: "Lainnya" },
  { ngaju: "dumah", indonesian: "Datang", category: "Lainnya" },
  { ngaju: "hakailing", indonesian: "Sekeliling", category: "Lainnya" },
  { ngaju: "hampari", indonesian: "Bersaudara", category: "Lainnya" },
  { ngaju: "hila", indonesian: "Arah", category: "Lainnya" },
  { ngaju: "hila ngawa", indonesian: "Arah hilir, sebelah hilir", category: "Lainnya" },
  { ngaju: "humbang", indonesian: "Bambu", category: "Lainnya" },
  { ngaju: "ije kaupun", indonesian: "Serumpun", category: "Lainnya" },
  { ngaju: "ingaliling", indonesian: "Dikelilingi", category: "Lainnya" },
  { ngaju: "jambatan", indonesian: "Jembatan", category: "Lainnya" },
  { ngaju: "kahain", indonesian: "Sebesar", category: "Lainnya" },
  { ngaju: "kajariae", indonesian: "Akhirnya", category: "Lainnya" },
  { ngaju: "kalepahan", indonesian: "Kehabisan", category: "Lainnya" },
  { ngaju: "kalonen", indonesian: "Dunia", category: "Lainnya" },
  { ngaju: "kaput pijem", indonesian: "Gelap gulita", category: "Lainnya" },
  { ngaju: "kasalan", indonesian: "Kesalahan", category: "Lainnya" },
  { ngaju: "kawu", indonesian: "Abu", category: "Lainnya" },
  { ngaju: "lime", indonesian: "Lima", category: "Lainnya" },
  { ngaju: "malihi", indonesian: "Meninggal", category: "Lainnya" },
  { ngaju: "mamancarkan", indonesian: "Memancarkan", category: "Lainnya" },
  { ngaju: "mampakalah", indonesian: "Mengalahkan", category: "Lainnya" },
  { ngaju: "mampatei", indonesian: "Membunuh", category: "Lainnya" },
  { ngaju: "mamua", indonesian: "Berbuah", category: "Lainnya" },
  { ngaju: "maneweng", indonesian: "Menebang", category: "Lainnya" },
  { ngaju: "mangat", indonesian: "Supaya", category: "Lainnya" },
  { ngaju: "mangganti", indonesian: "Mengganti", category: "Lainnya" },
  { ngaju: "manukep", indonesian: "Mendekat", category: "Lainnya" },
  { ngaju: "manyarang", indonesian: "Menyerang", category: "Lainnya" },
  { ngaju: "manteng", indonesian: "Berani", category: "Lainnya" },
  { ngaju: "paling ngawa", indonesian: "Paling hilir", category: "Lainnya" },
  { ngaju: "paninggalan", indonesian: "Peninggalan", category: "Lainnya" },
  { ngaju: "pusit", indonesian: "Pecah", category: "Lainnya" },
  { ngaju: "sabangsa", indonesian: "Sebangsa", category: "Lainnya" },
  { ngaju: "sanaman", indonesian: "Besi", category: "Lainnya" },
  { ngaju: "saran", indonesian: "Tapi", category: "Lainnya" },
  { ngaju: "saritan", indonesian: "Cerita", category: "Lainnya" },
  { ngaju: "tamparan", indonesian: "Awal", category: "Lainnya" },
  { ngaju: "tasebar", indonesian: "Tersebar", category: "Lainnya" },
  { ngaju: "kaput", indonesian: "Gelap", category: "Lainnya" },
  { ngaju: "karambang", indonesian: "Pagar", category: "Lainnya" },
  { ngaju: "katantraman", indonesian: "Ketentraman", category: "Lainnya" },
  { ngaju: "lewo", indonesian: "Desa, kampung", category: "Lainnya" },
  { ngaju: "maisi", indonesian: "Mengisi", category: "Lainnya" },
  { ngaju: "malihi kalonen", indonesian: "Meninggal di dunia", category: "Lainnya" },
  { ngaju: "mamili", indonesian: "Membeli", category: "Lainnya" },
  { ngaju: "mampalawa", indonesian: "Menerangi", category: "Lainnya" },
  { ngaju: "mampendeng", indonesian: "Mendirikan", category: "Lainnya" },
  { ngaju: "mananjong", indonesian: "Berjalan", category: "Lainnya" },
  { ngaju: "mangalindung", indonesian: "Melindungi", category: "Lainnya" },
  { ngaju: "mangganggu", indonesian: "Mengganggu", category: "Lainnya" },
  { ngaju: "manggau", indonesian: "Mencari", category: "Lainnya" },
  { ngaju: "manumon", indonesian: "Menurut", category: "Lainnya" },
  { ngaju: "manyewot", indonesian: "Menyebut", category: "Lainnya" },
  { ngaju: "mihir", indonesian: "Menarik", category: "Lainnya" },
  { ngaju: "paling gaju", indonesian: "Paling hulu", category: "Lainnya" },
  { ngaju: "panduduke", indonesian: "Penduduknya", category: "Lainnya" },
  { ngaju: "pijem", indonesian: "Gulita", category: "Lainnya" },
  { ngaju: "ramai", indonesian: "Ramai", category: "Lainnya" },
  { ngaju: "salembang", indonesian: "Tak beruku", category: "Lainnya" },
  { ngaju: "sapanjang", indonesian: "Sepanjang", category: "Lainnya" },
  { ngaju: "saritae", indonesian: "Ceritanya", category: "Lainnya" },
  { ngaju: "tanjakah", indonesian: "Terlempar", category: "Lainnya" },
  { ngaju: "tantame", indonesian: "Termasuk", category: "Lainnya" },
  { ngaju: "uras", indonesian: "Semua, seluruh", category: "Lainnya" },
  { ngaju: "akibate", indonesian: "Akibatnya", category: "Lainnya" },
  { ngaju: "anak tabela", indonesian: "Anak muda", category: "Lainnya" },
  { ngaju: "andau male", indonesian: "Hari kemarin", category: "Lainnya" },
  { ngaju: "awae", indonesian: "Bekasnya", category: "Lainnya" },
  { ngaju: "nadohen", indonesian: "Kuat, erat", category: "Lainnya" },
];

export const CONVERSATIONS = [
  {
    id: "makan-minum",
    title: "Makan dan Minum",
    dialogues: [
      { speaker: "A", text: "Salamat kuman.", language: "Dayak Ngaju" },
      { speaker: "B", text: "Tarima kasih.", language: "Dayak Ngaju" },
      { speaker: "A", text: "Jangan lupa mihup dan kuman.", language: "Dayak Ngaju" },
      { speaker: "B", text: "Ie, tarima kasih.", language: "Dayak Ngaju" },
    ]
  },
  {
    id: "belajar-dayak",
    title: "Belajar Bahasa",
    dialogues: [
      { speaker: "A", text: "Itah balajar Bahasa Dayak Ngaju.", language: "Dayak Ngaju" },
      { speaker: "B", text: "Ie, aku balajar.", language: "Dayak Ngaju" },
    ]
  },
  {
    id: "kegiatan-mandui",
    title: "Kegiatan Mandi",
    dialogues: [
      { speaker: "A", text: "Andau itah mandui?", language: "Dayak Ngaju" },
      { speaker: "B", text: "Andau sorenya aku mandui.", language: "Dayak Ngaju" },
    ]
  },
  {
    id: "lobby-school",
    title: "Menyapa di Sekolah",
    dialogues: [
      { speaker: "Siswa A", text: "Tabe, narai kabar?", language: "Dayak Ngaju" },
      { speaker: "Siswa B", text: "Kabar bahalap. Ikau narai kabar?", language: "Dayak Ngaju" },
    ]
  }
];
