
export const INITIAL_VOCABULARY = [
  { ngaju: "narai", indonesian: "Apa", category: "Umum" },
  { ngaju: "pue", indonesian: "Adik", category: "Keluarga" },
  { ngaju: "kaka", indonesian: "Kakak", category: "Keluarga" },
  { ngaju: "bapa", indonesian: "Bapak", category: "Keluarga" },
  { ngaju: "uma", indonesian: "Ibu", category: "Keluarga" },
  { ngaju: "bue", indonesian: "Kakek", category: "Keluarga" },
  { ngaju: "tambo", indonesian: "Nenek", category: "Keluarga" },
  { ngaju: "anak", indonesian: "Anak", category: "Keluarga" },
  { ngaju: "esun", indonesian: "Cucu", category: "Keluarga" },
  { ngaju: "kawal", indonesian: "Teman", category: "Umum" },
  { ngaju: "oloh", indonesian: "Orang", category: "Umum" },
  { ngaju: "hatalla", indonesian: "Tuhan", category: "Umum" },
  { ngaju: "pambelum", indonesian: "Hidup", category: "Umum" },
  { ngaju: "pampatei", indonesian: "Mati", category: "Umum" },
  { ngaju: "humila", indonesian: "Jahat", category: "Sifat" },
  { ngaju: "bahalap", indonesian: "Baik", category: "Sifat" },
  { ngaju: "bagawi", indonesian: "Bekerja", category: "Kegiatan" },
  { ngaju: "balajar", indonesian: "Belajar", category: "Kegiatan" },
  { ngaju: "kuman", indonesian: "Makan", category: "Kegiatan" },
  { ngaju: "mihup", indonesian: "Minum", category: "Kegiatan" },
  { ngaju: "batiruh", indonesian: "Tidur", category: "Kegiatan" },
  { ngaju: "misik", indonesian: "Bangun", category: "Kegiatan" },
  { ngaju: "mandui", indonesian: "Mandi", category: "Kegiatan" },
  { ngaju: "mentai", indonesian: "Jemur", category: "Kegiatan" },
  { ngaju: "mili", indonesian: "Beli", category: "Kegiatan" },
  { ngaju: "manjual", indonesian: "Jual", category: "Kegiatan" },
  { ngaju: "hadari", indonesian: "Lari", category: "Kegiatan" },
  { ngaju: "nandai", indonesian: "Mendaki", category: "Kegiatan" },
  { ngaju: "penda", indonesian: "Bawah", category: "Arah" },
  { ngaju: "hunjut", indonesian: "Atas", category: "Arah" },
  { ngaju: "gantau", indonesian: "Kanan", category: "Arah" },
  { ngaju: "sambil", indonesian: "Kiri", category: "Arah" },
  { ngaju: "ngaju", indonesian: "Hulu", category: "Arah" },
  { ngaju: "ngawa", indonesian: "Hilir", category: "Arah" },
  { ngaju: "uran", indonesian: "Hujan", category: "Alam" },
  { ngaju: "andau", indonesian: "Hari", category: "Waktu" },
  { ngaju: "malem", indonesian: "Malam", category: "Waktu" },
  { ngaju: "jewu", indonesian: "Besok", category: "Waktu" },
  { ngaju: "benteng andau", indonesian: "Siang", category: "Waktu" },
  { ngaju: "sungei", indonesian: "Sungai", category: "Alam" },
  { ngaju: "danau", indonesian: "Danau", category: "Alam" },
  { ngaju: "tasik", indonesian: "Laut", category: "Alam" },
  { ngaju: "bukit", indonesian: "Bukit", category: "Alam" },
  { ngaju: "gunung", indonesian: "Gunung", category: "Alam" },
  { ngaju: "petak", indonesian: "Tanah", category: "Alam" },
  { ngaju: "kayu", indonesian: "Kayu", category: "Alam" },
  { ngaju: "kembang", indonesian: "Bunga", category: "Alam" },
  { ngaju: "buah", indonesian: "Buah", category: "Alam" },
  { ngaju: "handipe", indonesian: "Ular", category: "Hewan" },
  { ngaju: "bakei", indonesian: "Monyet", category: "Hewan" },
  { ngaju: "hadangan", indonesian: "Kerbau", category: "Hewan" },
  { ngaju: "sapi", indonesian: "Sapi", category: "Hewan" },
  { ngaju: "bawoi", indonesian: "Babi", category: "Hewan" },
  { ngaju: "manuk", indonesian: "Ayam", category: "Hewan" },
  { ngaju: "bebek", indonesian: "Bebek", category: "Hewan" },
  { ngaju: "asu", indonesian: "Anjing", category: "Hewan" },
  { ngaju: "pusa", indonesian: "Kucing", category: "Hewan" },
  { ngaju: "burung", indonesian: "Burung", category: "Hewan" },
  { ngaju: "lauk", indonesian: "Ikan", category: "Hewan" },
  { ngaju: "udang", indonesian: "Udang", category: "Hewan" },
  { ngaju: "kanai", indonesian: "Perut", category: "Anggota Tubuh" },
  { ngaju: "pusar", indonesian: "Pusar", category: "Anggota Tubuh" },
  { ngaju: "tulang", indonesian: "Tulang", category: "Anggota Tubuh" },
  { ngaju: "upak", indonesian: "Kulit", category: "Anggota Tubuh" },
  { ngaju: "balau", indonesian: "Rambut", category: "Anggota Tubuh" },
  { ngaju: "takuluk", indonesian: "Kepala", category: "Anggota Tubuh" },
  { ngaju: "bau", indonesian: "Muka", category: "Anggota Tubuh" },
  { ngaju: "mate", indonesian: "Mata", category: "Anggota Tubuh" },
  { ngaju: "urung", indonesian: "Hidung", category: "Anggota Tubuh" },
  { ngaju: "pinding", indonesian: "Telinga", category: "Anggota Tubuh" },
  { ngaju: "nyame", indonesian: "Mulut", category: "Anggota Tubuh" },
  { ngaju: "kasinga", indonesian: "Gigi", category: "Anggota Tubuh" },
  { ngaju: "biwih", indonesian: "Bibir", category: "Anggota Tubuh" },
  { ngaju: "jela", indonesian: "Lidah", category: "Anggota Tubuh" },
  { ngaju: "uyat", indonesian: "Leher", category: "Anggota Tubuh" },
  { ngaju: "lenge", indonesian: "Tangan", category: "Anggota Tubuh" },
  { ngaju: "pai", indonesian: "Kaki", category: "Anggota Tubuh" },
  { ngaju: "silu", indonesian: "Kuku", category: "Anggota Tubuh" },
  { ngaju: "seluwar", indonesian: "Celana", category: "Benda" },
  { ngaju: "rumah", indonesian: "Rumah", category: "Benda" },
  { ngaju: "batunggang", indonesian: "Pintu", category: "Benda" },
  { ngaju: "basenguk", indonesian: "Jendela", category: "Benda" },
  { ngaju: "rajin", indonesian: "Rajin", category: "Sifat" },
  { ngaju: "salamat kuman", indonesian: "Selamat makan", category: "Sapaan" },
  { ngaju: "buah buah", indonesian: "Hati-hati", category: "Sapaan" },
  { ngaju: "manyarak", indonesian: "Menyisir", category: "Kegiatan" },
];

export const CONVERSATIONS = [
  {
    id: "makan-minum",
    title: "Makan dan Minum",
    dialogues: [
      { speaker: "A", text: "Salamat kuman.", language: "Dayak Ngaju" },
      { speaker: "B", text: "Tarima kasih.", language: "Dayak Ngaju" },
      { speaker: "A", text: "Jangan lupa mihup dan kuman.", language: "Dayak Ngaju" },
      { speaker: "B", text: "Ie, tarima kasih.", language: "Dayak Ngaju" },
    ]
  },
  {
    id: "belajar-dayak",
    title: "Belajar Bahasa",
    dialogues: [
      { speaker: "A", text: "Itah balajar Bahasa Dayak Ngaju.", language: "Dayak Ngaju" },
      { speaker: "B", text: "Ie, aku balajar.", language: "Dayak Ngaju" },
    ]
  },
  {
    id: "kegiatan-mandui",
    title: "Kegiatan Mandi",
    dialogues: [
      { speaker: "A", text: "Andau itah mandui?", language: "Dayak Ngaju" },
      { speaker: "B", text: "Andau sorenya aku mandui.", language: "Dayak Ngaju" },
    ]
  },
  {
    id: "lobby-school",
    title: "Menyapa di Sekolah",
    dialogues: [
      { speaker: "Siswa A", text: "Tabe, narai kabar?", language: "Dayak Ngaju" },
      { speaker: "Siswa B", text: "Kabar bahalap. Ikau narai kabar?", language: "Dayak Ngaju" },
    ]
  }
];
